backend:
  image: docker
  services: 
    - docker:dnid
  before_script: 
    - cd backend 

  script:
    - docker build -f Dockerfile -t thiagomes/backend .
    - docker login -u thiagomes -p @#Vasco123
    - docker push thiagomes/backend